<a href="https://colab.research.google.com/github/ShoryaDubey/ML/blob/main/BasicML_Steps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [ ]:
with open("/content/sample_data/example.csv", "w") as f:
    f.write("""Age,Glucose,BloodPressure,Gender,Outcome
25,120,80,M,0
30,,85,F,1
35,140,,M,0
,130,90,F,1
28,115,75,M,0
""")


In [ ]:
df = pd.read_csv('/content/sample_data/example.csv')
# X = df.iloc[:, :-1]
# Y = df.iloc[:, -1]

X = df.drop('Outcome', axis=1)
Y = df['Outcome']

Checking for null value

In [ ]:
missing_data = X.isnull().sum()

print(missing_data)

Age              1
Glucose          1
BloodPressure    1
Gender           0
dtype: int64


Handling Missing Values

In [ ]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X.iloc[:, 0:3])
X.iloc[:, 0:3] = imputer.transform(X.iloc[:, 0:3])

Encoding Catagorical labels in dataset

In [ ]:
ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [3])
    ],
    remainder='passthrough'
)

X = ct.fit_transform(X)

print(X)

[[  0.     1.    25.   120.    80.  ]
 [  1.     0.    30.   126.25  85.  ]
 [  0.     1.    35.   140.    82.5 ]
 [  1.     0.    29.5  130.    90.  ]
 [  0.     1.    28.   115.    75.  ]]


Simple Lable Encoder (0, 1)

In [ ]:
le = LabelEncoder()
Y = le.fit_transform(Y)

In [ ]:
print(Y)

[0 1 0 1 0]


Splitting the data into train and test sets.

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
    X, Y, test_size = 0.2, random_state=42)

In [ ]:
print(x_train)

[[  0.    1.   28.  115.   75. ]
 [  0.    1.   35.  140.   82.5]
 [  0.    1.   25.  120.   80. ]
 [  1.    0.   29.5 130.   90. ]]


In [ ]:
print(x_test)

[[  1.     0.    30.   126.25  85.  ]]


In [ ]:
sc = StandardScaler()
x_train[:, 2:] = sc.fit_transform(x_train[:, 2:])
x_test[:, 2:] = sc.transform(x_test[:, 2:])

In [ ]:
print(x_train)

[[ 0.          1.         -0.37886012 -1.1717002  -1.27017059]
 [ 0.          1.          1.54988233  1.43207802  0.11547005]
 [ 0.          1.         -1.20546403 -0.65094455 -0.34641016]
 [ 1.          0.          0.03444183  0.39056673  1.5011107 ]]


In [ ]:
print(x_test)

[[1.         0.         0.17220915 0.         0.57735027]]
