<a href="https://colab.research.google.com/github/ShoryaDubey/ML/blob/main/Multilinear_Reg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("farhanmd29/50-startups")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/50-startups


In [ ]:
import pandas as pd

df = pd.read_csv('/kaggle/input/50-startups/50_Startups.csv')

In [ ]:
print(df)

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       

In [ ]:
X = df.iloc[:, 1:-1].values
Y = df.iloc[:, -1].values

print(X)

[[136897.8 471784.1 'New York']
 [151377.59 443898.53 'California']
 [101145.55 407934.54 'Florida']
 [118671.85 383199.62 'New York']
 [91391.77 366168.42 'Florida']
 [99814.71 362861.36 'New York']
 [147198.87 127716.82 'California']
 [145530.06 323876.68 'Florida']
 [148718.95 311613.29 'New York']
 [108679.17 304981.62 'California']
 [110594.11 229160.95 'Florida']
 [91790.61 249744.55 'California']
 [127320.38 249839.44 'Florida']
 [135495.07 252664.93 'California']
 [156547.42 256512.92 'Florida']
 [122616.84 261776.23 'New York']
 [121597.55 264346.06 'California']
 [145077.58 282574.31 'New York']
 [114175.79 294919.57 'Florida']
 [153514.11 0.0 'New York']
 [113867.3 298664.47 'California']
 [153773.43 299737.29 'New York']
 [122782.75 303319.26 'Florida']
 [105751.03 304768.73 'Florida']
 [99281.34 140574.81 'New York']
 [139553.16 137962.62 'California']
 [144135.98 134050.07 'Florida']
 [127864.55 353183.81 'New York']
 [182645.56 118148.2 'Florida']
 [153032.06 107138.38 '

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [2])],
    remainder='passthrough'
)
X = ct.fit_transform(X)
print(X)

[[0.0 0.0 1.0 136897.8 471784.1]
 [1.0 0.0 0.0 151377.59 443898.53]
 [0.0 1.0 0.0 101145.55 407934.54]
 [0.0 0.0 1.0 118671.85 383199.62]
 [0.0 1.0 0.0 91391.77 366168.42]
 [0.0 0.0 1.0 99814.71 362861.36]
 [1.0 0.0 0.0 147198.87 127716.82]
 [0.0 1.0 0.0 145530.06 323876.68]
 [0.0 0.0 1.0 148718.95 311613.29]
 [1.0 0.0 0.0 108679.17 304981.62]
 [0.0 1.0 0.0 110594.11 229160.95]
 [1.0 0.0 0.0 91790.61 249744.55]
 [0.0 1.0 0.0 127320.38 249839.44]
 [1.0 0.0 0.0 135495.07 252664.93]
 [0.0 1.0 0.0 156547.42 256512.92]
 [0.0 0.0 1.0 122616.84 261776.23]
 [1.0 0.0 0.0 121597.55 264346.06]
 [0.0 0.0 1.0 145077.58 282574.31]
 [0.0 1.0 0.0 114175.79 294919.57]
 [0.0 0.0 1.0 153514.11 0.0]
 [1.0 0.0 0.0 113867.3 298664.47]
 [0.0 0.0 1.0 153773.43 299737.29]
 [0.0 1.0 0.0 122782.75 303319.26]
 [0.0 1.0 0.0 105751.03 304768.73]
 [0.0 0.0 1.0 99281.34 140574.81]
 [1.0 0.0 0.0 139553.16 137962.62]
 [0.0 1.0 0.0 144135.98 134050.07]
 [0.0 0.0 1.0 127864.55 353183.81]
 [0.0 1.0 0.0 182645.56 118148.2]

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.3, random_state=42
)

In [ ]:
from sklearn.linear_model import LinearRegression

lr =  LinearRegression()

lr.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_prid = lr.predict(x_test)
print(y_test)


[134307.35  81005.76  99937.59  64926.08 125370.37  35673.41 105733.54
 107404.34  97427.84 122776.86 141585.52 166187.94  89949.14 152211.77
 182901.99]


In [ ]:
import numpy as np
np.set_printoptions(precision=2)
np.concatenate((y_test.reshape(len(y_test), 1), y_prid.reshape(len(y_prid), 1)), axis=1)

array([[134307.35, 124534.97],
       [ 81005.76,  87774.97],
       [ 99937.59,  66526.35],
       [ 64926.08,  51449.86],
       [125370.37, 135871.56],
       [ 35673.41,  30152.04],
       [105733.54,  86689.89],
       [107404.34,  93650.28],
       [ 97427.84,  65015.73],
       [122776.86,  59338.12],
       [141585.52, 114219.69],
       [166187.94, 136418.99],
       [ 89949.14,  84839.62],
       [152211.77, 145029.5 ],
       [182901.99, 156414.16]])

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("satyajeetrai/medical-cost")

print("Path to dataset files:", path)


Path to dataset files: /kaggle/input/medical-cost


In [ ]:
import pandas as pd

df = pd.read_csv('/kaggle/input/medical-cost/dataset_.csv')
df.columns = df.columns.str.replace(" ", "_")
print(df)

      age     sex     bmi  children smoker     region  medical_charges
0      19  female  27.900         0    yes  southwest      16884.92400
1      18    male  33.770         1     no  southeast       1725.55230
2      28    male  33.000         3     no  southeast       4449.46200
3      33    male  22.705         0     no  northwest      21984.47061
4      32    male  28.880         0     no  northwest       3866.85520
...   ...     ...     ...       ...    ...        ...              ...
1333   50    male  30.970         3     no  northwest      10600.54830
1334   18  female  31.920         0     no  northeast       2205.98080
1335   18  female  36.850         0     no  southeast       1629.83350
1336   21  female  25.800         0     no  southwest       2007.94500
1337   61  female  29.070         0    yes  northwest      29141.36030

[1338 rows x 7 columns]


In [ ]:
print(df['region'].unique())
print(df['sex'].unique())

['southwest' 'southeast' 'northwest' 'northeast']
['female' 'male']


In [ ]:
X = df.iloc[:, :-1]
Y = df.iloc[:, -1].values

print(X)

      age     sex     bmi  children smoker     region
0      19  female  27.900         0    yes  southwest
1      18    male  33.770         1     no  southeast
2      28    male  33.000         3     no  southeast
3      33    male  22.705         0     no  northwest
4      32    male  28.880         0     no  northwest
...   ...     ...     ...       ...    ...        ...
1333   50    male  30.970         3     no  northwest
1334   18  female  31.920         0     no  northeast
1335   18  female  36.850         0     no  southeast
1336   21  female  25.800         0     no  southwest
1337   61  female  29.070         0    yes  northwest

[1338 rows x 6 columns]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['smoker'] = le.fit_transform(X['smoker'])
print(X['smoker'])

0       1
1       0
2       0
3       0
4       0
       ..
1333    0
1334    0
1335    0
1336    0
1337    1
Name: smoker, Length: 1338, dtype: int64


In [ ]:
print(X)

      age     sex     bmi  children  smoker     region
0      19  female  27.900         0       1  southwest
1      18    male  33.770         1       0  southeast
2      28    male  33.000         3       0  southeast
3      33    male  22.705         0       0  northwest
4      32    male  28.880         0       0  northwest
...   ...     ...     ...       ...     ...        ...
1333   50    male  30.970         3       0  northwest
1334   18  female  31.920         0       0  northeast
1335   18  female  36.850         0       0  southeast
1336   21  female  25.800         0       0  southwest
1337   61  female  29.070         0       1  northwest

[1338 rows x 6 columns]


In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [1,5])],
    remainder='passthrough'
)
X = ct.fit_transform(X)

In [ ]:
print(X)
print(Y)

[[ 1.    0.    0.   ... 27.9   0.    1.  ]
 [ 0.    1.    0.   ... 33.77  1.    0.  ]
 [ 0.    1.    0.   ... 33.    3.    0.  ]
 ...
 [ 1.    0.    0.   ... 36.85  0.    0.  ]
 [ 1.    0.    0.   ... 25.8   0.    0.  ]
 [ 1.    0.    0.   ... 29.07  0.    1.  ]]
[16884.92  1725.55  4449.46 ...  1629.83  2007.94 29141.36]


In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    X, Y, test_size = 0.5, random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(x_test)


In [ ]:
import numpy as np
np.set_printoptions(precision=2)
np.concatenate((y_test.reshape(len(y_test), 1), y_pred.reshape(len(y_pred), 1)), axis=1)

array([[ 9095.07,  9270.97],
       [ 5272.18,  7112.66],
       [29330.98, 36251.75],
       ...,
       [10381.48, 13557.68],
       [ 8515.76,  9212.84],
       [20745.99, 29888.03]])

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
rmse = mse**0.5
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MSE: 35276395.61025525
RMSE: 5939.393538927628
R2 Score: 0.7741831666132295
